Ejemplo que utiliza la implementación de PCA (Principal Component Analysis) de *scikit-learn* para reducir la dimensionalidad de un conjunto de datos.

Los datos corresponden al popular conjunto de datos **MNIST** para el reconocimiento de dígitos manuscritos. Contiene 784 atributos predictores (cada uno para el píxel de una imagen), además de un atributo de clase con 10 posibles clases asociadas a dígitos entre 0 y 9.

In [1]:
from keras.datasets import mnist

In [2]:
(X, y), (X_test, y_test) = mnist.load_data()

Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz
11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step

The data contains two files, but we will use only the training.csv file and assume we will split that data intro training and testing subsets.

In [3]:
X.shape

(60000, 28, 28)

El dataset tiene forma tridimensional (array 3D de numpy), pero usaremos reshape para "aplanar" los 28x28 pixels en 784 atributos dispuestos uno tras otro.

In [4]:
import pandas as pd

X_flattened = X.reshape(-1, 28 * 28) # Transforma tensor 3D en imagen 2D, manteniendo la primera dimensión (filas) inalterada con el -1
X = pd.DataFrame(X_flattened)

In [5]:
X

,0,1,2,3,4,5,6,7,8,9,...,774,775,776,777,778,779,780,781,782,783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
X.shape

(60000, 784)

In [7]:
y

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.2, random_state=42)

Dado que PCA es un algoritmo sensible a las escalas de datos, es importante **escalar los datos** antes de aplicarlo (incluso si todos los atributos se mueven en la misma escala de valores).

In [9]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

Comenzaremos aplicando **PCA** sobre los datos de entrenamiento para reducir su elevada dimensionalidad actual.

**IMPORTANTE**: En PCA, es recomendable elegir un número de dimensiones (atributos) que preserve la mayor parte de la varianza original de los datos, digamos alrededor del 95 % de la varianza. Esto ayudará a mantener la estructura y las propiedades originales de los datos en un nivel razonable, sin pérdida de información importante.

El hiperparámetro *n_components* permite especificar la razón de varianza deseada (0 a 1) o el número de atributos finales a utilizar.

In [10]:
from sklearn.decomposition import PCA

pca = PCA(n_components = 0.95)
X_train_reduced = pca.fit_transform(X_train_scaled)

# pca.fit(X_train_scaled)
# X_train_reduced = pca.transform(X_train_scaled)

In [11]:
X_train_reduced.shape

(48000, 325)

In [12]:
X_train_reduced = pd.DataFrame(X_train_reduced)
X_train_reduced

,0,1,2,3,4,5,6,7,8,9,...,315,316,317,318,319,320,321,322,323,324
0,-0.042850,-1.922173,-2.502337,7.964983,1.077381,-4.148513,-0.425776,-5.876309,5.392261,6.426217,...,0.684402,-0.446435,0.602439,-0.769761,-0.040244,0.014970,-0.013870,-1.336535,-1.093262,0.445452
1,8.159589,-4.496171,-4.742099,-2.320534,-8.645237,-7.728010,4.637402,-1.067832,3.591596,1.278361,...,-2.152462,-0.478290,-0.011454,0.248183,-0.373366,0.355062,0.145534,-0.122456,-1.392287,-0.530339
2,-7.504882,-3.719109,5.136624,-0.929010,-5.582463,0.784303,0.119790,-0.141546,0.874097,-5.488482,...,0.393893,0.047588,-0.011032,-0.203371,-0.300063,0.114123,0.021368,0.106091,0.023043,-0.208855
3,-2.565513,-6.309477,3.295843,-3.473859,1.079441,-0.543763,-5.584808,1.394799,3.941671,-2.405826,...,-0.216190,0.449714,-0.719795,0.725861,0.178438,0.190263,-0.017254,-0.521254,0.451128,0.711090
4,-8.050921,-0.898628,2.913307,-0.751697,-6.091275,-3.646365,-0.210335,0.156029,0.011015,-1.091831,...,-0.066988,-0.220629,0.227259,-0.267181,-0.029231,-0.098163,0.327994,-0.140119,0.026742,-0.076615
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47995,-2.289936,1.734848,4.226273,4.876930,2.965655,-0.513827,-0.311633,-3.131572,-2.619939,1.725717,...,-0.092272,-0.030267,0.368762,0.449703,-0.315540,-0.089261,-0.335972,0.020908,-0.579972,0.159859
47996,0.436061,17.903416,3.358243,4.930947,-4.220086,6.263674,-6.870976,7.311984,7.553666,-1.040716,...,-0.043833,-1.156748,-0.377582,0.937800,-0.932472,-0.390467,-1.035982,1.192052,-2.137390,0.934325
47997,10.277324,-9.286522,-1.825945,0.380016,2.371874,-5.031980,0.286289,3.280927,1.267502,0.075448,...,-0.270588,-0.410650,-0.100675,-0.418987,-0.102017,-0.367182,-0.046936,-0.232183,-0.047086,-0.465650
47998,10.297289,-12.412745,3.294376,2.399056,-2.223515,-0.669528,-3.400927,3.015931,1.800259,-2.297471,...,0.258599,-0.368006,-0.005462,-0.564216,0.083970,-0.174144,0.214714,-0.306916,-0.549343,-0.218316
47999,-2.877432,-0.812139,-1.447647,-3.836451,2.766923,0.585682,-3.604875,-2.867963,0.559424,2.020950,...,0.112908,0.354369,-0.039217,-0.035172,0.085199,-0.301420,-0.143925,0.113009,-0.234226,-0.119122

Aunque se ha conservado gran parte de la varianza de los datos originales (95%), ahora tenemos un conjunto de datos con aproximadamente el 40% de su tamaño original (atributos).

**Probar el dataset con dimensionalidad reducida, para entrenar y testear un clasificador**

In [13]:
from sklearn.linear_model import SGDClassifier

sgd_clf = SGDClassifier(random_state=42)
sgd_clf.fit(X_train_reduced, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_stochastic_gradient.py:738: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(

SGDClassifier(random_state=42)

¡No olvides lo siguiente!
Antes de usar los **datos de prueba** para las predicciones, deben aplicársele las mismas transformaciones que las realizadas sobre a los datos de entrenamiento transformados. Si bien ya están escalados, aún necesitamos aplicar la **transformación PCA** a nuestros datos de prueba.

In [14]:
X_test_reduced = pca.transform(X_test_scaled)
X_test_reduced.shape

(12000, 325)

In [15]:
X_test_reduced = pd. DataFrame(X_test_reduced)
X_test_reduced

,0,1,2,3,4,5,6,7,8,9,...,315,316,317,318,319,320,321,322,323,324
0,-2.679015,8.277977,-5.287089,1.474270,0.048930,-2.991258,-4.434629,7.473910,-1.945813,1.894230,...,-0.410862,0.582666,0.069252,-0.583674,1.006605,0.062709,0.064852,0.048063,-0.292100,0.144825
1,1.734583,0.123237,7.790288,6.524184,4.952981,-4.049326,1.052107,3.280566,-0.638430,2.174868,...,0.157116,-0.056543,0.169306,-0.121733,-0.009181,0.167353,-0.183352,0.075036,0.286682,0.487515
2,-3.094878,-6.566102,-0.658732,6.668936,2.371922,3.503016,2.300802,-1.646899,2.309551,-3.575805,...,0.211102,0.164016,0.006746,0.341734,-0.996982,-0.074437,-0.514399,0.217833,0.186776,0.351562
3,-6.808547,-0.042127,-5.013268,0.086345,3.489821,1.832052,6.400056,0.112159,3.236824,-2.668801,...,0.563700,-0.054823,0.252017,0.232015,-0.266853,-0.388246,-0.078104,0.631241,-0.111698,-0.479375
4,6.136303,-7.501538,5.127950,7.544228,3.644309,4.186035,-4.100879,2.452123,-9.716308,1.481760,...,0.046727,0.913697,-0.575724,0.273305,0.547863,0.172592,0.560969,-0.259511,-0.248819,0.525490
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,1.428448,-7.623603,4.061306,-3.004625,-0.758423,3.018704,-2.946906,0.472013,-6.835247,-0.586607,...,-0.067993,-0.214110,0.073197,-0.361127,0.275977,-0.505349,-1.230045,0.316295,0.000829,0.078140
11996,5.254567,4.652858,-8.407871,-4.628301,-2.600322,0.400978,-1.753160,-3.322686,0.840048,4.603079,...,0.276539,0.357685,-0.493122,0.569754,0.127827,0.397603,-0.429852,-0.421872,-0.121770,0.291866
11997,-5.338577,4.225801,-1.178442,1.536570,4.000923,-5.526088,-3.000575,-2.100226,0.260270,0.724964,...,0.289539,0.216026,-0.176288,0.086962,0.328368,-0.328196,0.641878,-0.020696,0.287229,-0.706762
11998,-0.213975,5.182710,-8.004796,-0.870224,4.178288,-4.327499,-1.613081,-0.354933,-2.938759,1.811855,...,-0.227713,0.199464,0.134537,0.288586,0.419676,-0.338610,0.205911,-0.194927,-0.059080,-0.837974
11999,4.568892,-0.150474,6.674439,-0.594109,1.868289,4.706506,3.331314,4.627923,-5.910824,0.768980,...,-0.185651,-0.110766,0.240528,-0.497561,0.578818,-0.622147,-0.683044,-0.039172,0.768844,0.187820

In [16]:
from sklearn.metrics import accuracy_score

y_pred = sgd_clf.predict(X_test_reduced)
accuracy_score(y_test, y_pred)

0.8966666666666666

In [17]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.94      0.96      1175
           1       0.97      0.95      0.96      1322
           2       0.91      0.88      0.90      1174
           3       0.92      0.84      0.88      1219
           4       0.93      0.91      0.92      1176
           5       0.90      0.81      0.85      1104
           6       0.97      0.94      0.95      1177
           7       0.95      0.91      0.93      1299
           8       0.64      0.92      0.75      1160
           9       0.92      0.85      0.88      1194

    accuracy                           0.90     12000
   macro avg       0.91      0.90      0.90     12000
weighted avg       0.91      0.90      0.90     12000

Para comprobar si la reducción de dimensionalidad ha sido útil, entrenaremos otro clasificador con la misma configuración que el anterior, pero utilizando la versión completa y escalada de nuestros datos (antes de haberles reducido la dimensionalidad).

**ADVERTENCIA**: Este proceso de entrenamiento tardará un tiempo; puedes tomar un breve descanso mientras se ejecuta.

In [18]:
sgd_clf_full = SGDClassifier(random_state=42)
sgd_clf_full.fit(X_train_scaled, y_train)

SGDClassifier(random_state=42)

In [19]:
y_pred_full = sgd_clf_full.predict(X_test_scaled)
accuracy_score(y_test, y_pred_full)

0.8978333333333334

In [20]:
print(classification_report(y_test, y_pred_full))

              precision    recall  f1-score   support

           0       0.98      0.94      0.96      1175
           1       0.97      0.95      0.96      1322
           2       0.91      0.88      0.89      1174
           3       0.92      0.85      0.88      1219
           4       0.93      0.91      0.92      1176
           5       0.90      0.82      0.86      1104
           6       0.96      0.94      0.95      1177
           7       0.95      0.92      0.93      1299
           8       0.64      0.92      0.76      1160
           9       0.92      0.86      0.89      1194

    accuracy                           0.90     12000
   macro avg       0.91      0.90      0.90     12000
weighted avg       0.91      0.90      0.90     12000

Con los datos de dimensionalidad reducida, no solo tarda menos en entrenarse el modelo, sino que también mantiene un rendimiento predictivo muy similar al entrenarse un clasificador con los mismos.

Ahora bien, podríamos preguntarnos: ¿qué tal si obtenemos una versión aún más "comprimida" de nuestros datos? Supongamos que mantenemos el 80 % de su varianza original. ¿Seguirá funcionando igual bien un clasificador SGD ante unos datos con dimensionalidad tan fuertemente reducida?

In [21]:
pca_80 = PCA(n_components = 0.80)
X_train_80 = pca_80.fit_transform(X_train_scaled)
X_test_80 = pca_80.transform(X_test_scaled)

In [22]:
X_train_80 = pd.DataFrame(X_train_80)
X_test_80 = pd.DataFrame(X_test_80)
X_train_80.shape

(48000, 146)

In [23]:
sgd_clf_80 = SGDClassifier(random_state=42)
sgd_clf_80.fit(X_train_80, y_train)

SGDClassifier(random_state=42)

In [24]:
y_pred_80 = sgd_clf_80.predict(X_test_80)
accuracy_score(y_test, y_pred_80)

0.8875833333333333